### ISSUE TITLE
ProductVersion too long for varchar(32)

### ISSUE THREAD

**Issue by GutmanskiK** [TomJerzak/seeder#9]
In table __SeedsHistory the column ProductVersion is too short for the SeederVersion = "1.0.11".

Exception for: dotnet seeder database update 

Npgsql.PostgresException: 22001: wartość zbyt długa dla typu znakowego zmiennego (32)
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()

**Comment by TomJerzak** [comment]
How many characters does the text have that throws an exception?

**Comment by TomJerzak** [comment]
The value consists of 33 fields. The Seeder.Core value will be shortened to Core.

**Comment by TomJerzak** [comment]
https://github.com/TomJerzak/seeder/commit/6c2c8e69335b0c909acdd41ee80e7239a1c0046d
